feat: atoma vision improvements
atoma-network/atoma-docs pull request #5
Opened 2024-06-19 17:34 UTC by jorgeantonio21

2024-06-20 13:08 UTC, joehill7 requested changes

2024-06-20 13:08 UTC, joehill7 commented on website/atoma-vision.md
> +
2. From 1., one can build decentralized protocols that interact with user owned vector embedding databases, while maintaining the users
privacy and data ownership. Further applications can be created using these features, such as interactive browsers that can have fine access to user preferences, without ever share user sensitive data with the exterior, etc.

Grammar -> decentralized protocols can be built that interact with user owned vector embedding databases while maintaining the users privacy and data ownership.

Grammar -> Further applications can be created using these features such as interactive browsers that can have fine access to user preferences without ever sharing sensitive user  data with the exterior.

2024-06-20 13:08 UTC, joehill7 commented on website/atoma-vision.md
> +3. DeFi automation strategies. Current DeFi protocols rely on heavy manual set up of key parameters, such as token emission rates, etc. These values can be tuned through AIs given the current market
Grammar -> 
3. DeFi automation strategies. Current DeFi protocols rely on heavy manual set up of key parameters, i.e token emission rates. These values can be tuned through AI given the current market conditions. Atoma enables this in a completely transparent way reducing any trust assumption on the DeFi protocol core team.

2024-06-20 13:08 UTC, joehill7 commented on website/atoma-vision.md
> +4. Generative AI content for Web3 applications. These include genetic NFTs that can adapt their features (through AI) on the user own blockchain activity or other personal/public available data, etc.
Grammar -> 4. Generative AI content for Web3 applications. These include genetic NFTs that can adapt their features (through AI) on the users own blockchain activity or other personal/public available data.

2024-06-20 13:08 UTC, joehill7 commented on website/atoma-vision.md
> +only possible through a decentralized AI inference protocol such as the Atoma Network.
Grammar -> 5. Autonomous smart agents that can interact with blockchains and protocols. It is only possible to achieve smart agents behaving on behalf of Web3 protocols if these agents are themselves transparently automated and controlled in a decentralized environment. This is only possible through a decentralized AI inference protocol such as the Atoma Network.

2024-06-24 10:37 UTC, jorgeantonio21 commented on website/atoma-vision.md
> +We envision that compute requirements will grow exponentially in the coming years, especially due to the advent of powerful generative AIs. Moreover, it is estimated that decentralized cloud/edge inf
Great !

2024-06-24 10:43 UTC, merged